Filter the no repeats fragments and add test stage
yangtcai/Ensembl-Repeat-Identification pull request #28
Opened 2022-06-23 13:14 UTC by yangtcai

I divide the dataset into train and test, so we can see how it performs on unseen sequences :D

2022-06-23 13:18 UTC, yangtcai commented
BTW, pandas is really great, when we filter the no repeats subsequence only needs 5 min on the laptop, so it makes sense!!!!

2022-06-23 15:40 UTC, williamstark01 requested changes
Very good job, as you say, 5 minutes is not too long for preparing the dataset (even though it can probably be optimized even further).

And I guess you are running an experiment with the new test set, looking forward to see how well it performs.

2022-06-23 15:40 UTC, williamstark01 commented on dataloader.py
> +from tqdm import tqdm
tqdm is a third party library

2022-06-23 15:40 UTC, williamstark01 commented on dataloader.py
> +            # produce sequence with overlap 500 of length 2000
obsolete comment

2022-06-24 07:14 UTC, yangtcai commented on dataloader.py
> +        index = random.randint(1, 5000)
this index is the index in the repeat_list we filterd in the `__init__`, the repeat_list will store the original index, so when we call `__getitem__(self, index)`, we use `repeat_list[index]` to get the original index, the original index is the position of subsequene.

2022-06-24 11:58 UTC, williamstark01 commented on dataloader.py
> +        index = random.randint(1, 5000)
Great, similar indexing with the one before filtering.

2022-06-24 11:59 UTC, merged